### ISSUE TITLE
Throws when tries to parse .d.ts file

### ISSUE THREAD

**Issue by Kamahl19** [nucleartux/i18next-scanner-typescript#1]
When I set extensions to `extensions: ['.ts', '.tsx']`, scanner throws when attempting to transpile `.d.ts` file.

**Comment by Kamahl19** [comment]
When I disable transforming Trans by not providing any extensions, it runs find, extracts all `t function`  fields but ignore all `<Trans />` components. So only half of the translations gets exported. Am I missing something? :)

**Comment by Kamahl19** [comment]
this needs to be added to the extension check
```
!path.basename(file.path).includes('.d.ts')
```

**Comment by nucleartux** [comment]
@Kamahl19 can I ask you to make a PR?

**Comment by Kamahl19** [comment]
Sure! https://github.com/nucleartux/i18next-scanner-typescript/pull/2
