### ISSUE TITLE
Trans component processing

### ISSUE THREAD

**Issue by jc-7** [nucleartux/i18next-scanner-typescript#6]
Hi. Looks like translations rendered with `Trans` component are  completely not scanned, at least they are not included in result.

I have tried different variants, but get no success at all.

After some debugging I think that `this.parser.parseTransFromString(outputText)` probably do not accept `outputText`, as it does not execute passed as 3rd arg optional callback.

Best regards

**Comment by gjou-tlnd** [comment]
Hi @jc-7 

Make sure this tsOption is applied (either by not providing arguments to typescriptTransform() or by providing the tsOptions)
```
    tsOptions: {
      target: "es2018",
    },
```

**Comment by badsyntax** [comment]
I can confirm setting the target fixed things for me. Thanks for the suggestion @gjou-tlnd
